# Generated by Django 5.1.3 on 2024-11-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="expression",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="KpiAssetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField()),
                ("result", models.CharField(max_length=100)),
                (
                    "expression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpi.kpi"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="KpiAssitLink",
        ),
    ]
