# Generated by Django 5.1.3 on 2024-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0002_alter_kpi_expression_kpiassetlink_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpiassetlink",
            old_name="expression",
            new_name="kpi_id",
        ),
    ]
