# Generated by Django 5.1.3 on 2024-11-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0003_rename_expression_kpiassetlink_kpi_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpiassetlink",
            unique_together={("asset_id", "kpi_id")},
        ),
    ]
